### ISSUE TITLE
SyntaxError: Named export 'stringifyPosition' not found. after fresh install

### ISSUE THREAD

**Issue by NatsuDragneelKl** [gravitano/nuxt3-tailwind-kit#5]
I work with yarn and after running yarn dev i got this error, any idea :(?

`file:///C:/xampp816/htdocs/nuxt3-tailwind-kit-main/.nuxt/dev/index.mjs:30
import { stringifyPosition } from 'file://C:/xampp816/htdocs/nuxt3-tailwind-kit-main/node_modules/unist-util-stringify-position/index.js';
         ^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'stringifyPosition' not found. The requested module 'file://C:/xampp816/htdocs/nuxt3-tailwind-kit-main/node_modules/unist-util-stringify-position/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'file://C:/xampp816/htdocs/nuxt3-tailwind-kit-main/node_modules/unist-util-stringify-position/index.js';
const { stringifyPosition } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)`

**Comment by gravitano** [comment]
What version of Node.js are you using?

**Comment by jorgec** [comment]
Running into this same problem, on Node 16.20

**Comment by thaikolja** [comment]
This issue also appears:

` ERROR  [@nuxtjs/i18n]: The vueI18n option is no longer be specified with object.                                                                                                                                                                                                                        07:09:07
It must be specified in the configuration file via the 'i18n.config' path.
About deprecated reason, see https://v8.i18n.nuxtjs.org/guide/migrating#change-the-route-key-rules-in-pages-option
About new configuration style, see https://v8.i18n.nuxtjs.org/getting-started/basic-usage#translate-with-vue-i18n

  It must be specified in the configuration file via the 'i18n.config' path.
  About deprecated reason, see https://v8.i18n.nuxtjs.org/guide/migrating#change-the-route-key-rules-in-pages-option
  About new configuration style, see https://v8.i18n.nuxtjs.org/getting-started/basic-usage#translate-with-vue-i18n
  at setup (node_modules/@nuxtjs/i18n/dist/module.mjs:1652:13)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:170:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:440:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2908:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:2969:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:534:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:48:20)

error Command failed with exit code 1.`

**Comment by gravitano** [comment]
Hi, can you guys try with [pnpm](https://pnpm.io/) instead?
